name: KiCad_CI

on:
  push:
    paths:
      - 'pcb/MC5000_Board.sch'
      - 'pcb/MC5000_Board.kicad_pcb'
      - 'pcb/modules/*.sch'
      - 'pcb/check_and_make_docs.kibot.yaml'
      - '.github/workflows/check_and_make_docs.yml'
  
  
jobs:
  make_docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: nerdyscout/kicad-exports@v2.2
        with:
          config: pcb/check_and_make_docs.kibot.yaml
          dir: 'pcb'
          board: 'pcb/MC5000_Board.kicad_pcb'
          schema: 'pcb/MC5000_Board.sch'
      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add pcb/docs
          git commit -m "Uodate pcb docs" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}