name: Build_App

on: push

#on:
#  push:
#    tags:
#      - v*

jobs:
  
  once:
      name: Create GitHub release
      runs-on: ubuntu-latest
      outputs:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
      steps:
        - name: Create a release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            draft: true
            prerelease: true
  
  build_gui_linux_x64:
    name: Create Linux GUI for x86_64
    runs-on: ubuntu-18.04
    if: ${{ false }}  # disable for now
    needs: once
    steps:
      - uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.12.2
        with:
          version: '5.12.8'
      - name: Install dependencies
        run: |
          sudo apt-get install -y libxcb* patchelf libgl1-mesa-dev
          cd gui
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod 755 linuxdeploy-x86_64.AppImage
          wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
          chmod 755 linuxdeploy-plugin-qt-x86_64.AppImage
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod 755 appimagetool-x86_64.AppImage
        shell: bash
      - name: Compile QT app
        run: |
          cd gui
          qmake
          make
        shell: bash
      - name: Make AppImage 
        run: |
          cd gui
          QML_SOURCES_PATHS=. ./linuxdeploy-x86_64.AppImage --plugin qt --appdir AppDir -d imagebuilder/MC5000.desktop -e MC5000-GUI -i icons/icon.png
          ./appimagetool-x86_64.AppImage AppDir
        shell: bash
      - uses: actions/upload-release-asset@v1
        name: Upload release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.once.outputs.upload_url }}
          asset_path: gui/MC5000-GUI-Linux-x86_64.AppImage
          asset_name: MC5000-GUI-Linux_x86_64.AppImage
          asset_content_type: application/octet-stream

  build_gui_linux_arm:
    name: Create Linux GUI for armhf and arm64
    runs-on: ubuntu-latest
    needs: once
    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu20.04
    steps:
      - uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Build GUI 
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          # Not required, but speeds up builds
          githubToken: ${{ github.token }} 
          # Mount the artifacts directory as /artifacts in the container
          dockerRunArgs: |
            --volume "${PWD}:${PWD}"
            --workdir "${PWD}"
            --device /dev/fuse
            --cap-add SYS_ADMIN 
            --security-opt apparmor:unconfined
          # The shell to run commands with in the container
          shell: /bin/sh
          install: |
            apt-get update
            apt-get install -y --no-install-recommends build-essential qtbase5-dev qt5-default qtdeclarative5-dev \
                      libqt5serialport5-dev wget git cmake zip unzip libfuse-dev autotools-dev patchelf \
                      automake libtool xxd desktop-file-utils pkg-config libglib2.0-dev libcairo2-dev \
                      libssl-dev libjpeg-dev libpng-dev cimg-dev ca-certificates
            apt-get clean
            git clone https://github.com/AppImage/AppImageKit.git --recursive --depth 1 && \
            cd AppImageKit && \
            cmake . && \
            make && \
            make install && \
            cd .. && \
            rm -r AppImageKit
            git clone https://github.com/linuxdeploy/linuxdeploy.git --recursive --depth 1 && \
            cd linuxdeploy && \
            cmake . && \
            make && \
            mv bin/linuxdeploy /usr/local/bin && \
            cd .. && \
            rm -r linuxdeploy
            git clone https://github.com/linuxdeploy/linuxdeploy-plugin-qt.git --recursive --depth 1 && \
            cd linuxdeploy-plugin-qt && \
            cmake . && \
            make && \
            mv bin/linuxdeploy-plugin-qt /usr/local/bin && \
            cd .. && \
            rm -r linuxdeploy-plugin-qt
          run: |
            cd gui
            qmake
            make
            QML_SOURCES_PATHS=. linuxdeploy --plugin qt --appdir AppDir -d imagebuilder/MC5000.desktop -e MC5000-GUI -i icons/icon.png
            appimagetool AppDir
      - uses: actions/upload-release-asset@v1
        name: Upload release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.once.outputs.upload_url }}
          asset_path: gui/MC5000*.AppImage
          asset_name: MC5000-GUI-Linux_${{ matrix.arch }}.AppImage
          asset_content_type: application/octet-stream

  build_gui_windows:
    name: Create Windows GUI
    runs-on: windows-2019
    if: ${{ false }}  # disable for now
    needs: once
    steps:
      - uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.12.2
        with:
          version: '5.12.8'
          arch: win64_mingw81
      - name: Compile QT app
        run: |
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cd gui
          qmake
          make
          windeployqt --qmldir . release/MC5000-GUI.exe
          rename release MC5000-GUI
        shell: cmd
      - uses: papeloto/action-zip@v1
        name: Zip files
        with:
          files: gui/MC5000-GUI/
          dest: MC5000-GUI-Windows_x86_64.zip
      - uses: actions/upload-release-asset@v1
        name: Upload release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.once.outputs.upload_url }}
          asset_path: MC5000-GUI-Windows_x86_64.zip
          asset_name: MC5000-GUI-Windows_x86_64.zip
          asset_content_type: application/octet-stream
          
  build_firmware:
    name: Build microcontroller firmware
    runs-on: ubuntu-latest
    if: ${{ false }}  # disable for now
    needs: once
    steps:
      - uses: actions/checkout@v2
      - name: Install SDCC compiler
        run: |
          wget https://qa.debian.org/watch/sf.php/sdcc/sdcc-4.1.0-amd64-unknown-linux2.5.tar.bz2
          tar xjvf sdcc-4.1.0-amd64-unknown-linux2.5.tar.bz2
          echo "$GITHUB_WORKSPACE/sdcc/bin" >> $GITHUB_PATH
      - name: Compile firmware
        run: |
          mkdir MC5000_firmware
          cd firmware/MC5000
          make
          cd ../BUZZER
          make
          cd ../DISPLAY
          make
          cd ../build
          cp *.ihx ../../MC5000_firmware
      - uses: papeloto/action-zip@v1
        name: Zip files
        with:
          files: MC5000_firmware
          dest: firmware.zip
      - uses: actions/upload-release-asset@v1
        name: Upload release assets   
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.once.outputs.upload_url }}
          asset_path: firmware.zip
          asset_name: MC5000-Padauk_PFS173_firmware.zip
          asset_content_type: application/octet-stream
    