name: Publish_release

on: push

jobs:

   
  step_one:
    name: First step
    runs-on: ubuntu-latest
    outputs:
      step_one_output: "Huhu"
    steps:
    - name: Sleep
      uses: jakejarvis/wait-action@master
      with:
        time: '1s'    
          
  step_two:
    name: Second step
    runs-on: ubuntu-latest
    needs: step_one
    steps:
    - name: Sleep
      uses: jakejarvis/wait-action@master
      with:
        time: '1s'
  
  step_three:
    name: Third step
    runs-on: ubuntu-latest
    needs: step_two
    env:
        STEP1_OUT: ${{ needs.step_two.needs.step_one.outputs.step_one_output }}
    steps:
    - name: Talk
      run: |
        echo $STEP1_OUT