name: Publish_release

on: push

jobs:

   
  step_one:
    name: Wait 5s
    runs-on: ubuntu-latest
    outputs:
      step_one_output: "Huhu"
    steps:
    - name: Sleep
      uses: jakejarvis/wait-action@master
      with:
        time: '5s'    
          
  step_two:
    name: Wait 5s
    runs-on: ubuntu-latest
    needs: step_one
    steps:
    - name: Sleep
      uses: jakejarvis/wait-action@master
      with:
        time: '5s'
  
  step_three:
    name: Wait 5s
    runs-on: ubuntu-latest
    needs: step_two
    steps:
    - name: Talk
      run: |
        echo "${ needs.step_two.needs.step_one.outputs.step_one_output }"