name: Publish_release

on:
  release:
    types: [prereleased, released, edited]
    
jobs:
  staple_osx_app:
    name: Staple notarization to MacOS GUI
    runs-on: macos-10.15
    steps:
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: tags/${GITHUB_REF}
          file: MC5000-GUI_MacOS-x86_64.dmg
        token: ${{ secrets.YOUR_TOKEN }}
      - name: Staple app
        run: |
          xcrun stapler staple "MC5000-GUI_MacOS-x86_64.dmg"
      - uses: svenstaro/upload-release-action@v2
        name: Upload stapled asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: MC5000-GUI_MacOS-x86_64.dmg
          tag: ${GITHUB_REF}
          overwrite: true