name: Build_mac_testp

on: push

jobs:
  
  once:
      name: Create GitHub release
      runs-on: ubuntu-latest
      outputs:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
      steps:
        - name: Create a release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            draft: true
            prerelease: true
  
  build_gui_osx:
    name: Create MacOS GUI for x86_64
    runs-on: macos-latest
    needs: once
    steps:
      - uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.12.2
      - name: Compile QT app
        run: |
          cd gui
          qmake
          make
        shell: bash
      - name: Package app 
        env:
        run: |
          cd gui
          macdeployqt MC5000-GUI.app -qmldir=.. -dmg
        shell: bash
      - uses: actions/upload-release-asset@v1
        name: Upload release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.once.outputs.upload_url }}
          asset_path: gui/MC5000-GUI.dmg
          asset_name: MC5000-GUI_MacOS-x86_64-unsigned.dmg
          asset_content_type: application/octet-stream
