name: test

on: push

jobs:
  build_gui_osx:
    name: Create MacOS GUI for x86_64
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Test stuff
        env:
          DEV_USER: ${{ secrets.APPLE_DEV_PASS }}
          DEV_PW: ${{ secrets.APPLE_DEV_USER }}
          DEV_CERT: ${{ secrets.APPLE_DEV_CERT }}
        run: |
          echo $DEV_CERT | base64 --decode > certificate.p12
          security create-keychain -p "$DEV_PW" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$DEV_PW" build.keychain
          security import certificate.p12 -k build.keychain -P "$DEV_PW" -T /usr/bin/codesign
          security find-identity -v
          set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$DEV_PW" build.keychain
          DEV_CERT_ID=$(security find-identity -v | grep "Developer ID Application" | awk -F"[()]" '{print $3}')
          codesign -vvv --deep --strict --options=runtime --sign $DEV_PW MC5000-GUI.app pcb
          